# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:6.9.4
clone:
  depth: full

templates:
  - build: &build
      name: build
      caches:
        - node
      script:
        - npm install
        - npm run lint
        - npm run lint:css
        - npm test
  - deploy: &deploy
      name: deploy
      script:
        - git commit -am 'disable node_modules cache' --allow-empty
        - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD

pipelines:
  # pipeline for non-master branch
  default:
    - step: *build
  branches:
    # pipeline for master branch only
    master:
      - step: *build
      - step: *deploy